x-logging: &default-logging
  driver: json-file
  options:
    max-size: "10m"
    max-file: "5"

services:
  registry:
    image: registry:3.0.0
    container_name: infra-registry
    restart: unless-stopped
    environment:
      OTEL_TRACES_EXPORTER: none
      REGISTRY_HTTP_ADDR: 0.0.0.0:5000
      REGISTRY_HTTP_HOST: https://${REGISTRY_HOST}
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_HTTP_SECRET: ${REGISTRY_HTTP_SECRET}
    security_opt:
      - no-new-privileges:true
    volumes:
      - registry-data:/var/lib/registry
      - ${REGISTRY_AUTH_FILE}:/auth/htpasswd:ro
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.docker.network=${PROXY_NETWORK}
      - traefik.http.routers.registry.rule=Host(`${REGISTRY_HOST}`)
      - traefik.http.routers.registry.entrypoints=websecure
      - traefik.http.routers.registry.tls=true
      - traefik.http.routers.registry.tls.certresolver=letsencrypt
      - traefik.http.services.registry.loadbalancer.server.port=5000
    logging: *default-logging

  registry-ui:
    image: joxit/docker-registry-ui:2.5.7
    container_name: infra-registry-ui
    restart: unless-stopped
    environment:
      SINGLE_REGISTRY: "true"
      REGISTRY_TITLE: Docker Registry UI
      PULL_URL: ${REGISTRY_HOST}
      DELETE_IMAGES: "true"
      SHOW_CONTENT_DIGEST: "true"
      SHOW_CATALOG_NB_TAGS: "true"
      CATALOG_MIN_BRANCHES: "1"
      CATALOG_MAX_BRANCHES: "1"
      TAGLIST_PAGE_SIZE: "100"
      CATALOG_ELEMENTS_LIMIT: "1000"
      REGISTRY_SECURED: "true"
      NGINX_PROXY_PASS_URL: http://registry:5000
    security_opt:
      - no-new-privileges:true
    depends_on:
      - registry
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.docker.network=${PROXY_NETWORK}
      - traefik.http.routers.registry-ui.rule=Host(`${REGISTRY_UI_HOST}`)
      - traefik.http.routers.registry-ui.entrypoints=websecure
      - traefik.http.routers.registry-ui.tls=true
      - traefik.http.routers.registry-ui.tls.certresolver=letsencrypt
      - traefik.http.services.registry-ui.loadbalancer.server.port=80
    logging: *default-logging

volumes:
  registry-data:
    name: registry-data

networks:
  proxy:
    external: true
    name: ${PROXY_NETWORK}
